### ISSUE TITLE
NumPy 1.22.2 is causing the build to fail on Windows with Python 3.8 and 3.9

### ISSUE THREAD

**Issue by moorepants** [conda-forge/pydy-feedstock#21]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm getting an error only on Windows with Python 3.8 and 3.9 (not 3.7):

```
INFO conda_build.utils:shutil_move_more_retrying(2098): shutil.move(work)=D:\bld\pydy_1643965080368\work, dest=D:\bld\pydy_1643965080368\work_moved_pydy-0.6.0-py38haa244fe_0_win-64)
Reloading output folder: D:\bld
bld/win-64                
bld/noarch                
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-mambabuild-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\boa\cli\mambabuild.py", line 239, in main
    call_conda_build(action, config)
  File "C:\Miniconda\lib\site-packages\boa\cli\mambabuild.py", line 211, in call_conda_build
    result = api.build(
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 186, in build
    return build_tree(
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 3094, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2884, in test
    environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,
  File "C:\Miniconda\lib\site-packages\conda_build\environ.py", line 904, in create_env
    display_actions(actions, index)
  File "C:\Miniconda\lib\site-packages\conda\exports.py", line 236, in display_actions
    actions['LINK'] = [index[d] for d in actions['LINK']]
  File "C:\Miniconda\lib\site-packages\conda\exports.py", line 236, in <listcomp>
    actions['LINK'] = [index[d] for d in actions['LINK']]
KeyError: Dist(channel='conda-forge', dist_name='numpy-1.22.2-py38hcf66579_0', name='numpy', fmt='.tar.bz2', version='1.22.2', build_string='py38hcf66579_0', build_number=0, base_url=None, platform=None)
##[error]Cmd.exe exited with code '1'.
```

NumPy 1.22 just came out today I think.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by moorepants** [comment]
No longer seems to be a problem.

**Comment by moorepants** [comment]
See #26
